# Generated by Django 2.2.3 on 2019-07-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='test_field',
            field=models.IntegerField(default=0),
        ),
    ]
