# Generated by Django 2.2.3 on 2019-07-22 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttest', '0005_auto_20190722_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonChild',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contenttest.Person')),
                ('third_name', models.CharField(max_length=50)),
            ],
            bases=('contenttest.person',),
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
