# Generated by Django 2.2.3 on 2019-07-22 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttest', '0006_personchild'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personchild',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CountPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_count', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='contenttest.Person')),
            ],
        ),
    ]
