# Generated by Django 2.2.3 on 2019-08-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttest', '0010_car_caroption_caruser_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='user',
        ),
        migrations.AddField(
            model_name='star',
            name='star_id',
            field=models.IntegerField(default=0),
        ),
    ]
