# Generated by Django 2.2.3 on 2019-08-07 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttest', '0011_auto_20190807_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starset', to='contenttest.Car'),
        ),
    ]
