# Generated by Django 2.1.5 on 2019-09-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttest', '0013_auto_20190807_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_set', related_query_name='star', to='contenttest.Car'),
        ),
    ]
